//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traningcenter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class traningcenterEntities : DbContext
    {
        public traningcenterEntities()
            : base("name=traningcenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Instructors_View> Instructors_View { get; set; }
    }
}
